spring:
  mysql:
    data: #主数据库配置
      jdbc-url: "jdbc:mysql://localhost:3306/app_data?useSSL=false&allowPublicKeyRetrieval=true"
      username: "root"
      password: "123456"
      driver-class-name: "com.mysql.jdbc.Driver"
    log: #日志数据库配置
      jdbc-url: "jdbc:mysql://localhost:3306/app_log?useSSL=false&allowPublicKeyRetrieval=true"
      username: "root"
      password: "123456"
      driver-class-name: "com.mysql.jdbc.Driver"
  redis:
    database: 3 #数据库序号
    host: "localhost" #数据库服务器地址
    port: 6379 #数据库服务器端口
    password: "123456789" #数据库服务器密码
    timeout: 4096 #连接超时时间
    jedis:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1 #最大阻塞时间 -1:无限制
        max-idle: 2 #最大空闲连接数
        min-idle: 1 #最小空闲连接数

wechat: # 微信配置
  appid: "wx43b87dc62794c2e7"
  mchid: "1498569742"
  secret: "8bed3389b49a1e55e932c16b3d24ae6f"
  mp: # 微信公众号配置
    appid: "wx26c57657ab9c434c"
    secret: "a679cf4f6007b000b889e3d808f8c79a"

aliSms: # 阿里云短信接口配置
  accessKeyId: "LTAICl3wP0ua3wQb"
  accessSecret: "d9gHPd4jujw20WBPcuRNcZIzPgwvro"
  sign: "天天摸鱼"
  authCode: "SMS_158050408"
  passCode: "SMS_158051452"
